baseURL = 'https://halannhile.github.io/'
languageCode = 'en-us'
title = "Home"
theme = 'PaperMod'

[params]
  author = 'Nhi'
  description = "Nhi's blog"

  [params.homeInfoParams]
    title = "👋 Hi, I'm Nhi"
    content = """Writing about AI topics that have recently fascinated me. No AI-generated content, just my own thoughts. "Ancora Imparo"."""

  [params.assets]
    favicon = "favicon.ico"
    theme_color = "#2e2e33"
    msapplication_TileColor = "#2e2e33"

    [[params.socialIcons]]
      name = "github"
      url = "https://github.com/halannhile"
      title = "GitHub"

[menu]
  [[menu.main]]
    name = "Posts"
    url = "/"
    weight = 10
  [[menu.main]]
    name = "Archive"
    url = "/archives/"
    weight = 20
  [[menu.main]]
    name = "Search"
    url = "/search/"
    weight = 30
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 40
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 50

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    noClasses = false

[outputs]
  home = ['HTML', 'RSS', 'JSON']
